### ISSUE TITLE
Define VN-2000 Projections

### ISSUE THREAD

**Issue by lepetitchu** [opengeoshub/HCMGIS#5]
Hiện tại plugin có hỗ trợ khai báo hệ tọa độ VN-2000, trong đó tham số chuyển datum là:
+towgs84=-191.9044129,-39.30318279,-111.45032835, -0.00928836, 0.01975479, -0.004274, 0.252906278
Tuy nhiên những tham số này (theo văn bản 05/2007/QĐ-BTNMT ngày 27/02/2007) là áp dụng cho phương thức chuyển Coordinate Frame / EPSG:9607. Còn theo chuẩn của **PROJ.4** thì lại sử dụng phương thức chuyển **Position Vector / EPSG:9606**. Hai phương thức này cùng sử dụng công thức Bursa/Wolf nhưng ngược dấu góc xoay trục tọa độ, sai lệch tọa độ giữa 2 kiểu chuyển này vào khoảng 0.5m.
Do đó, định nghĩa hệ VN-2000 cho QGIS, PostGIS thì cần đổi dấu 3 tham số góc xoay trục tọa độ, nên chuỗi tham số phải là: 
+towgs84=-191.9044129,-39.30318279,-111.45032835, **0.00928836, -0.01975479, 0.004274,** 0.252906278
Tham khảo: http://proj.maptools.org/gen_parms.html

**Comment by huynhphanson** [comment]
> Hiện tại plugin có hỗ trợ khai báo hệ tọa độ VN-2000, trong đó tham số chuyển datum là: +towgs84=-191.9044129,-39.30318279,-111.45032835, -0.00928836, 0.01975479, -0.004274, 0.252906278 Tuy nhiên những tham số này (theo văn bản 05/2007/QĐ-BTNMT ngày 27/02/2007) là áp dụng cho phương thức chuyển Coordinate Frame / EPSG:9607. Còn theo chuẩn của **PROJ.4** thì lại sử dụng phương thức chuyển **Position Vector / EPSG:9606**. Hai phương thức này cùng sử dụng công thức Bursa/Wolf nhưng ngược dấu góc xoay trục tọa độ, sai lệch tọa độ giữa 2 kiểu chuyển này vào khoảng 0.5m. Do đó, định nghĩa hệ VN-2000 cho QGIS, PostGIS thì cần đổi dấu 3 tham số góc xoay trục tọa độ, nên chuỗi tham số phải là: +towgs84=-191.9044129,-39.30318279,-111.45032835, **0.00928836, -0.01975479, 0.004274,** 0.252906278 Tham khảo: http://proj.maptools.org/gen_parms.html

Ôi thánh thần, cảm ơn anh rất nhiều
