### ISSUE TITLE
Plugin showing as needing update

### ISSUE THREAD

**Issue by Saijin-Naib** [opengeoshub/HCMGIS#6]
Due to what appears to be a parsing issue with the QGIS Plugin Repository, your plugin is showing as out of date, despite being fully up to date.

I've filed a QGIS issue here:  
https://github.com/qgis/QGIS/issues/34019

**Comment by thangqd** [comment]
Please update to HCMGIS version20.2.20 http://plugins.qgis.org/plugins/HCMGIS/version/20.2.20/. The error caused by the version name. Thanks
